In [844]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import sklearn 
import seaborn as sns

# Model training

In [845]:
data = pd.read_csv("data/train.csv")
data

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [846]:
data.describe()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
count,1460.000000,1460.000000,1201.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1452.000000,1460.000000,...,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000
mean,730.500000,56.897260,70.049958,10516.828082,6.099315,5.575342,1971.267808,1984.865753,103.685262,443.639726,...,94.244521,46.660274,21.954110,3.409589,15.060959,2.758904,43.489041,6.321918,2007.815753,180921.195890
std,421.610009,42.300571,24.284752,9981.264932,1.382997,1.112799,30.202904,20.645407,181.066207,456.098091,...,125.338794,66.256028,61.119149,29.317331,55.757415,40.177307,496.123024,2.703626,1.328095,79442.502883
min,1.000000,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,34900.000000
25%,365.750000,20.000000,59.000000,7553.500000,5.000000,5.000000,1954.000000,1967.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,2007.000000,129975.000000
50%,730.500000,50.000000,69.000000,9478.500000,6.000000,5.000000,1973.000000,1994.000000,0.000000,383.500000,...,0.000000,25.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,163000.000000
75%,1095.250000,70.000000,80.000000,11601.500000,7.000000,6.000000,2000.000000,2004.000000,166.000000,712.250000,...,168.000000,68.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,214000.000000
max,1460.000000,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,...,857.000000,547.000000,552.000000,508.000000,480.000000,738.000000,15500.000000,12.000000,2010.000000,755000.000000

In [847]:
data.shape

(1460, 81)

# Check correlation

In [848]:
data.corr()['SalePrice'].sort_values(ascending=False)

SalePrice        1.000000
OverallQual      0.790982
GrLivArea        0.708624
GarageCars       0.640409
GarageArea       0.623431
TotalBsmtSF      0.613581
1stFlrSF         0.605852
FullBath         0.560664
TotRmsAbvGrd     0.533723
YearBuilt        0.522897
YearRemodAdd     0.507101
GarageYrBlt      0.486362
MasVnrArea       0.477493
Fireplaces       0.466929
BsmtFinSF1       0.386420
LotFrontage      0.351799
WoodDeckSF       0.324413
2ndFlrSF         0.319334
OpenPorchSF      0.315856
HalfBath         0.284108
LotArea          0.263843
BsmtFullBath     0.227122
BsmtUnfSF        0.214479
BedroomAbvGr     0.168213
ScreenPorch      0.111447
PoolArea         0.092404
MoSold           0.046432
3SsnPorch        0.044584
BsmtFinSF2      -0.011378
BsmtHalfBath    -0.016844
MiscVal         -0.021190
Id              -0.021917
LowQualFinSF    -0.025606
YrSold          -0.028923
OverallCond     -0.077856
MSSubClass      -0.084284
EnclosedPorch   -0.128578
KitchenAbvGr    -0.135907
Name: SalePrice, dtype: float64

In [849]:
# Drop some features that are negatively correlated with the goal
data=data.drop(['Id','BsmtFinSF2', 'BsmtHalfBath','MiscVal','LowQualFinSF','YrSold','OverallCond','MSSubClass','EnclosedPorch','KitchenAbvGr'], axis = 1)
data

,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,...,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MoSold,SaleType,SaleCondition,SalePrice
0,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,...,0,0,0,NaN,NaN,NaN,2,WD,Normal,208500
1,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,Gtl,...,0,0,0,NaN,NaN,NaN,5,WD,Normal,181500
2,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,...,0,0,0,NaN,NaN,NaN,9,WD,Normal,223500
3,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,...,0,0,0,NaN,NaN,NaN,2,WD,Abnorml,140000
4,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,Gtl,...,0,0,0,NaN,NaN,NaN,12,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,...,0,0,0,NaN,NaN,NaN,8,WD,Normal,175000
1456,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,...,0,0,0,NaN,MnPrv,NaN,2,WD,Normal,210000
1457,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,...,0,0,0,NaN,GdPrv,Shed,5,WD,Normal,266500
1458,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,...,0,0,0,NaN,NaN,NaN,4,WD,Normal,142125
1459,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,...,0,0,0,NaN,NaN,NaN,6,WD,Normal,147500

In [850]:
X = data.drop('SalePrice', axis=1)
print(X)
y = data['SalePrice'].values.reshape(-1,1)

     MSZoning  LotFrontage  LotArea Street Alley LotShape LandContour  \
0          RL         65.0     8450   Pave   NaN      Reg         Lvl
1          RL         80.0     9600   Pave   NaN      Reg         Lvl
2          RL         68.0    11250   Pave   NaN      IR1         Lvl
3          RL         60.0     9550   Pave   NaN      IR1         Lvl
4          RL         84.0    14260   Pave   NaN      IR1         Lvl
...       ...          ...      ...    ...   ...      ...         ...
1455       RL         62.0     7917   Pave   NaN      Reg         Lvl
1456       RL         85.0    13175   Pave   NaN      Reg         Lvl
1457       RL         66.0     9042   Pave   NaN      Reg         Lvl
1458       RL         68.0     9717   Pave   NaN      Reg         Lvl
1459       RL         75.0     9937   Pave   NaN      Reg         Lvl

     Utilities LotConfig LandSlope  ... OpenPorchSF 3SsnPorch ScreenPorch  \
0       AllPub    Inside       Gtl  ...          61         0           0
1       AllPub       FR2       Gtl  ...           0         0           0
2       AllPub    Inside       Gtl  ...          42         0           0
3       AllPub    Corner       Gtl  ...          35         0           0
4       AllPub       FR2       Gtl  ...          84         0           0
...        ...       ...       ...  ...         ...       ...         ...
1455    AllPub    Inside       Gtl  ...          40         0           0
1456    AllPub    Inside       Gtl  ...           0         0           0
1457    AllPub    Inside       Gtl  ...          60         0           0
1458    AllPub    Inside       Gtl  ...           0         0           0
1459    AllPub    Inside       Gtl  ...          68         0           0

     PoolArea PoolQC  Fence  MiscFeature  MoSold SaleType SaleCondition
0           0    NaN    NaN          NaN       2       WD        Normal
1           0    NaN    NaN          NaN       5       WD        Normal
2           0    NaN    NaN          NaN       9       WD        Normal
3           0    NaN    NaN          NaN       2       WD       Abnorml
4           0    NaN    NaN          NaN      12       WD        Normal
...       ...    ...    ...          ...     ...      ...           ...
1455        0    NaN    NaN          NaN       8       WD        Normal
1456        0    NaN  MnPrv          NaN       2       WD        Normal
1457        0    NaN  GdPrv         Shed       5       WD        Normal
1458        0    NaN    NaN          NaN       4       WD        Normal
1459        0    NaN    NaN          NaN       6       WD        Normal

[1460 rows x 70 columns]

In [851]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25)

In [852]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(1095, 70)
(365, 70)
(1095, 1)
(365, 1)

In [853]:
len(X_train),len(X_test)

(1095, 365)

In [854]:
# Chekcing the percentage of Null values in all the columns
print('Percentage of Missing Values in each column is as follows:')
print(round(X_train.isnull().sum()/len(X_train.index)*100,2).sort_values(ascending=False)[ round(X_train.isnull().sum()/len(X_train.index),2) > 0 ] )

Percentage of Missing Values in each column is as follows:
PoolQC          99.63
MiscFeature     96.07
Alley           93.88
Fence           81.28
FireplaceQu     47.40
LotFrontage     17.72
GarageType       5.21
GarageCond       5.21
GarageYrBlt      5.21
GarageFinish     5.21
GarageQual       5.21
BsmtFinType2     2.56
BsmtFinType1     2.47
BsmtExposure     2.47
BsmtCond         2.47
BsmtQual         2.47
MasVnrType       0.55
MasVnrArea       0.55
dtype: float64

In [855]:
#let's drop some features have large missing value

X_train=X_train.drop(['PoolQC', 'MiscFeature','Alley','Fence','FireplaceQu','LotFrontage'], axis = 1)
X_train

,MSZoning,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,...,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,3SsnPorch,ScreenPorch,PoolArea,MoSold,SaleType,SaleCondition
612,RL,11885,Pave,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,...,TA,Y,160,122,0,0,0,11,WD,Normal
982,RL,3182,Pave,Reg,Lvl,AllPub,Inside,Gtl,Blmngtn,Norm,...,TA,Y,100,16,0,0,0,3,WD,Normal
1303,RL,8688,Pave,Reg,Lvl,AllPub,Inside,Gtl,Somerst,Norm,...,TA,Y,208,59,0,0,0,4,WD,Normal
353,RM,8520,Pave,Reg,Lvl,AllPub,Inside,Gtl,OldTown,Norm,...,TA,Y,106,0,0,0,0,5,WD,Normal
702,RL,12438,Pave,IR1,Lvl,AllPub,Inside,Gtl,StoneBr,Norm,...,TA,Y,324,100,0,0,0,7,New,Partial
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1388,RL,14892,Pave,IR1,HLS,AllPub,CulDSac,Gtl,Gilbert,Norm,...,TA,Y,201,39,0,0,0,10,WD,Normal
1322,RL,10186,Pave,IR1,Lvl,AllPub,Inside,Gtl,NoRidge,Norm,...,TA,Y,240,39,0,0,0,6,WD,Normal
544,RL,17104,Pave,IR1,Lvl,AllPub,Inside,Gtl,Gilbert,Norm,...,TA,Y,100,24,0,0,0,9,New,Partial
90,RL,7200,Pave,Reg,Lvl,AllPub,Inside,Gtl,NAmes,Norm,...,TA,Y,0,29,0,0,0,7,WD,Normal
785,RL,9790,Pave,Reg,Lvl,AllPub,Inside,Gtl,NWAmes,Feedr,...,TA,Y,0,0,0,197,0,9,WD,Normal

# Filter missing data

In [856]:

def missing(data):
    for col in data.columns:
        if data[col].dtypes=='object':
            data[col].fillna(data[col].mode()[0],inplace=True)
        elif data[col].dtypes=='int64' or data[col].dtypes=='float64':
            data[col].fillna(data[col].mean(),inplace=True) 
    return data

In [857]:
X_train= missing(X_train)

In [858]:
X_train.isnull().values.any()

False

# Filter the number of numerical features and the number of categorical features

In [859]:

numerical_col_train = []
category_col_train = []
for i in X_train.columns:
    if X_train[i].dtypes != 'O':
        numerical_col_train.append(i)
    else:
        category_col_train.append(i)
print('There are', len(numerical_col_train) ,'numerical features in the train dataset')
print('There are', len(category_col_train), 'categorical features in the train dataset')

There are 26 numerical features in the train dataset
There are 38 categorical features in the train dataset

In [860]:
print(numerical_col_train)

['LotArea', 'OverallQual', 'YearBuilt', 'YearRemodAdd', 'MasVnrArea', 'BsmtFinSF1', 'BsmtUnfSF', 'TotalBsmtSF', '1stFlrSF', '2ndFlrSF', 'GrLivArea', 'BsmtFullBath', 'FullBath', 'HalfBath', 'BedroomAbvGr', 'TotRmsAbvGrd', 'Fireplaces', 'GarageYrBlt', 'GarageCars', 'GarageArea', 'WoodDeckSF', 'OpenPorchSF', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'MoSold']

In [861]:
print(category_col_train)

['MSZoning', 'Street', 'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2', 'Heating', 'HeatingQC', 'CentralAir', 'Electrical', 'KitchenQual', 'Functional', 'GarageType', 'GarageFinish', 'GarageQual', 'GarageCond', 'PavedDrive', 'SaleType', 'SaleCondition']

# Encoding categorical_features

In [862]:
one_hot_encoder = OneHotEncoder(sparse = False)
caterogy_onehot_encoded = pd.DataFrame(one_hot_encoder.fit_transform(X_train[category_col_train]))
caterogy_onehot_encoded.columns = one_hot_encoder.get_feature_names_out(category_col_train)
caterogy_onehot_encoded.index = np.arange(1, len(X_train)+1)                
caterogy_onehot_encoded
X_train.drop(category_col_train, axis=1, inplace=True)
X_train = pd.concat([X_train.reset_index(), caterogy_onehot_encoded.reset_index()], axis=1)
X_train

,index,LotArea,OverallQual,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtUnfSF,TotalBsmtSF,1stFlrSF,...,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,612,11885,8,2001,2001,108.0,990,309,1299,1299,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
1,982,3182,7,2007,2007,16.0,0,1266,1266,1266,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1303,8688,7,2005,2005,228.0,0,1616,1616,1616,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
3,353,8520,6,1928,2003,0.0,0,624,624,720,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
4,702,12438,8,2006,2006,466.0,0,1234,1234,1264,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1090,1388,14892,9,2006,2007,160.0,1320,426,1746,1746,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
1091,1322,10186,7,1992,1992,0.0,674,76,750,1061,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
1092,544,17104,7,2006,2006,0.0,554,100,654,664,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1093,90,7200,4,1950,1950,0.0,0,0,0,1040,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
1094,785,9790,6,1967,1967,0.0,251,491,1372,1342,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0

In [863]:
X_train.isnull().values.any()

False

In [864]:
# to sure that we didn't have any null
# X_train.fillna(0, inplace=True)

Scaling
We will scale the features that have a spread distribution:

In [865]:
X_train[numerical_col_train].head(6)

,LotArea,OverallQual,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtUnfSF,TotalBsmtSF,1stFlrSF,2ndFlrSF,...,Fireplaces,GarageYrBlt,GarageCars,GarageArea,WoodDeckSF,OpenPorchSF,3SsnPorch,ScreenPorch,PoolArea,MoSold
0,11885,8,2001,2001,108.0,990,309,1299,1299,573,...,1,2001.0,2,531,160,122,0,0,0,11
1,3182,7,2007,2007,16.0,0,1266,1266,1266,0,...,1,2007.0,2,388,100,16,0,0,0,3
2,8688,7,2005,2005,228.0,0,1616,1616,1616,0,...,0,2005.0,3,834,208,59,0,0,0,4
3,8520,6,1928,2003,0.0,0,624,624,720,0,...,0,2005.0,2,484,106,0,0,0,0,5
4,12438,8,2006,2006,466.0,0,1234,1234,1264,1312,...,1,2006.0,3,666,324,100,0,0,0,7
5,9477,5,1966,1966,65.0,340,524,864,892,0,...,0,1966.0,1,264,0,0,0,0,0,10

# SCALING NUMERIC FEATURES

In [866]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train.loc[:,numerical_col_train] = scaler.fit_transform(X_train[numerical_col_train])
X_test.loc[:,numerical_col_train] = scaler.transform(X_test[numerical_col_train])
X_train[numerical_col_train].head(6)

,LotArea,OverallQual,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtUnfSF,TotalBsmtSF,1stFlrSF,2ndFlrSF,...,Fireplaces,GarageYrBlt,GarageCars,GarageArea,WoodDeckSF,OpenPorchSF,3SsnPorch,ScreenPorch,PoolArea,MoSold
0,0.108750,1.389321,0.993937,0.785747,0.028481,1.201338,-0.583242,0.549450,0.349035,0.528939,...,0.592438,0.947313,0.329453,0.288504,0.534762,1.157977,-0.128395,-0.277548,-0.059667,1.771810
1,-0.673948,0.657924,1.193428,1.076584,-0.477545,-0.969089,1.588673,0.474745,0.263718,-0.797383,...,0.592438,1.197966,0.329453,-0.393626,0.058590,-0.465740,-0.128395,-0.277548,-0.059667,-1.259646
2,-0.178770,0.657924,1.126931,0.979638,0.688515,-0.969089,2.382999,1.267075,1.168599,-0.797383,...,-0.944813,1.114415,1.690779,1.733858,0.915700,0.192938,-0.128395,-0.277548,-0.059667,-0.880714
3,-0.193879,-0.073474,-1.433213,0.882693,-0.565549,-0.969089,0.131652,-0.978615,-1.147897,-0.797383,...,-0.944813,1.114415,0.329453,0.064308,0.106207,-0.710829,-0.128395,-0.277548,-0.059667,-0.501782
4,0.158483,1.389321,1.160180,1.028111,1.997583,-0.969089,1.516049,0.402303,0.258547,2.239500,...,0.592438,1.156190,1.690779,0.932474,1.836300,0.820980,-0.128395,-0.277548,-0.059667,0.256082
5,-0.107812,-0.804871,-0.169765,-0.910802,-0.208031,-0.223690,-0.095298,-0.435303,-0.703213,-0.797383,...,-0.944813,-0.514828,-1.031872,-0.985124,-0.735030,-0.710829,-0.128395,-0.277548,-0.059667,1.392878

In [867]:
X_train.head(6)

,index,LotArea,OverallQual,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtUnfSF,TotalBsmtSF,1stFlrSF,...,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,612,0.108750,1.389321,0.993937,0.785747,0.028481,1.201338,-0.583242,0.549450,0.349035,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
1,982,-0.673948,0.657924,1.193428,1.076584,-0.477545,-0.969089,1.588673,0.474745,0.263718,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1303,-0.178770,0.657924,1.126931,0.979638,0.688515,-0.969089,2.382999,1.267075,1.168599,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
3,353,-0.193879,-0.073474,-1.433213,0.882693,-0.565549,-0.969089,0.131652,-0.978615,-1.147897,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
4,702,0.158483,1.389321,1.160180,1.028111,1.997583,-0.969089,1.516049,0.402303,0.258547,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
5,1356,-0.107812,-0.804871,-0.169765,-0.910802,-0.208031,-0.223690,-0.095298,-0.435303,-0.703213,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0

# Training the Algorithm

In [868]:
len(X_train),len(y_train)

(1095, 1095)

In [869]:

from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

print ('Coefficients: ', regressor.intercept_)

print ('Coefficients: ', regressor.coef_)

Coefficients:  [31632.80012585]
Coefficients:  [[ 6.16994542e-01  1.50221769e+04  1.05202670e+04  6.04490713e+03
   4.61296262e+03  3.43122090e+03  8.23788548e+03 -6.28960474e+02
   6.86604313e+03  4.96382124e+03  1.16552407e+04  1.98408377e+04
   2.73890204e+02  4.28798190e+02 -2.18314008e+02 -3.89580083e+03
   1.13807793e+03 -2.76284034e+02 -7.04475619e+02  3.60658172e+03
   1.59481885e+03  2.46991728e+03  1.53907003e+03  1.33395268e+03
   1.41203338e+03  1.12389172e+03 -5.02980005e+02 -2.63988606e+00
  -2.28383901e+04  1.55656541e+04  3.53895588e+03  4.04326710e+03
  -3.09487029e+02 -1.41808808e+04  1.41808808e+04  2.07797240e+03
   2.29578438e+02 -4.45215498e+03  2.14460414e+03  4.22061406e+03
   5.17232489e+03 -1.27029277e+04  3.30998874e+03  5.69153688e+03
  -5.69153688e+03  4.00622245e+03  9.52028582e+03 -6.61164177e+03
  -9.75912923e+03  2.84426273e+03  4.16440472e+04  4.38680437e+04
  -8.55120910e+04  6.00267639e+03  4.25852081e+03  6.83797113e+03
  -9.64545320e+03 -6.53514011e+03  1.55973487e+04 -1.36718823e+04
  -9.81678792e+03  5.25516272e+02 -7.40547087e+03 -2.27932953e+04
  -1.15710917e+04  2.11509298e+04 -1.02817730e+04  2.16635928e+04
   1.80364817e+04 -1.28259018e+04  3.22184712e+02 -9.10920730e+03
  -4.57282180e+03 -2.08833412e+03  3.40014443e+04 -1.63730956e+04
   8.29358828e+03 -3.86492424e+03 -8.12224395e+02  8.61818700e+03
  -7.17261568e+03  9.52423452e+03 -1.16880475e+04 -1.26740308e+03
  -4.81015765e+03  1.14729510e+04  1.65892611e+04  9.81923691e+03
   2.03630354e+04  4.72050061e+04 -1.36865879e+05  4.28893398e+04
   1.67715157e+04  2.96344062e+02 -3.97913800e+03 -8.70171214e+03
  -4.38700958e+03 -2.44117453e+02  9.74528558e+03  8.17697961e+03
  -2.71459445e+04  4.25143218e+03 -1.78860851e+03  9.17347615e+02
   6.08762552e+03 -2.04865309e+04 -2.40972629e+04 -2.85939043e+04
  -2.06390571e+04 -1.73543812e+04  1.11171136e+05 -6.07064310e+05
   5.07406837e+04  1.98415398e+05  1.65102631e+05  3.64999388e+04
   4.84188805e+04  6.21049031e+04  4.57818738e+04  1.36966664e+04
   6.02486492e+03 -2.49257742e+04  1.62112266e+04 -3.83571254e+03
  -5.58246125e+03 -2.67313073e+03  8.94454908e+03 -8.43400945e+02
  -1.57612041e+03  9.45748751e+03 -3.79078078e+02 -1.39306172e+04
  -5.88499052e+02 -1.00918014e+04  1.19632554e+03 -1.67192557e+03
   3.62735953e+03 -3.83571254e+03  1.89766131e+04  4.48104447e+03
   2.07634516e+03 -4.34942235e+03 -1.86934019e+04 -7.48585908e+01
  -1.42522591e+04  1.19421411e+03  7.97130349e+03  1.52521336e+04
  -1.80595761e+03 -5.48129889e+03 -2.17705068e+03  3.93659004e+02
   7.26469056e+03  1.00790209e+04  6.57141664e+03 -7.42238657e+03
  -9.22805095e+03  1.38363306e+04 -9.28257645e+02  5.74833173e+02
  -1.29129426e+04 -5.69963498e+02  1.76480787e+03  5.08711072e+03
   3.08989369e+03  5.57530023e+03  3.07727966e+03 -1.85943922e+04
   9.79677284e+03  3.04790629e+03 -8.43459597e+03 -4.41008316e+03
  -6.82865686e+03 -1.80150648e+03  6.07118561e+03  2.55897773e+03
  -3.50792971e+03  1.60900636e+04 -5.35946133e+03 -7.22267251e+03
   1.08784487e+03  4.12538788e+02  4.82147886e+03 -5.12964060e+03
  -2.46766342e+03  1.27544150e+03  1.13886201e+04 -4.31672326e+03
   1.01738310e+04 -8.15111862e+03 -4.51895258e+03 -4.57565670e+03
   3.12120503e+03 -1.13569417e+03 -1.21282318e+04  3.81050428e+03
  -1.12203005e+04  1.75525172e+04  1.46036128e+03 -1.07101845e+03
   2.15920753e+02 -6.05263586e+02 -3.74269861e+03  3.74269861e+03
  -7.19294297e+02 -2.18295148e+03 -1.96669207e+03  6.07118561e+03
  -1.20224777e+03  1.34107909e+04 -1.68282641e+03 -5.60160470e+03
  -6.12635981e+03 -9.24375603e+02 -1.36974444e+04  9.68379755e+03
   1.49646751e+04  1.13424076e+04 -4.83060295e+04  2.69369694e+04
  -1.43158975e+04  3.14246518e+03 -1.41422609e+03  4.06460052e+03
   3.87181312e+03  4.65124474e+03  9.10420289e+02 -3.32340854e+03
   2.41298825e+03  1.47733563e+05 -3.58072186e+04 -2.54674433e+04
  -5.77941552e+04 -2.86647454e+04 -1.40189170e+05  2.80739324e+04
   3.49095585e+04  4.39409002e+04  3.32647793e+04  2.91999419e+03
  -4.63410048e+03  1.71410629e+03 -8.09496353e+03  1.99506661e+04
   2.56941445e+04  4.04543280e+03 -8.85458724e+03 -1.06156605e+04
  -1.53921388e+04  5.55610333e+02 -7.28850373e+03 -1.52345603e+04
   1.23936753e+04  3.67325695e+02 -5.88096736e+03 -6.28651355e+03
   1.46410402e+04]]

In [870]:
len(X_train),len(y_train)

(1095, 1095)